site_name: Nonadiabatic Nanoreactor Use Guide
site_url: https://PieriLab.github.io/nanr-mkdocs-only/

theme:
  name: material
  font:
    text: Quicksand
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.integrate

extra_css:
  - styles/frutiger_aero.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - 🏠 Home: index.md
  - 1. 🔍 Seam Sampling: 1_seam_sampling.md
  - 2. 🌌 Clustering: 2_clustering.md
  - 3. ⏳ MECI Optimization: 3_meci_optimization.md
  - 4. 🍦 Cone Sampling: 4_cone_sampling.md
  - 5. 🏖️ Relaxation: 5_relaxation.md

